# settings_synthetic.R — runs Option B on a SYNTHETIC stratified survey, to show how a
# stratified estimate and its interval work. The data are computer-generated (see
# data-raw/build_workbooks.py, synthetic()); they are not field observations, and the area
# sits at 0° N, 0° E so it describes no real place.
#   SETTINGS_FILE <- "settings_synthetic.R"; source("run_option_B.R")

source("settings_example.R")   # start from the worked example's settings, then change what differs

PROJECT <- list(
  title        = "SYNTHETIC stratified survey — calculation demonstration",
  question_B   = "How much sediment organic carbon is in this (synthetic) eelgrass area, and how precisely do the cores pin down the mean?",
  area_habitat = "SYNTHETIC eelgrass area: dense meadow, sparse meadow, and a channel edge that was not sampled",
  survey_dates = "SYNTHETIC — 15 July 2026",
  design       = "Stratified random: plots placed at random within the dense and sparse strata (synthetic)",
  methods      = "SYNTHETIC: 7.0 cm corer, 2 cm slices to 10 cm then 5 cm; compaction measured; OC on most cores, LOI on some",
  data_source  = "Generated by data-raw/build_workbooks.py (seed 2026). Not field data.",
  prepared_by  = "Blue Carbon Eelgrass Workshop"
)

WORKBOOK <- "data/synthetic/Eelgrass_Carbon_DigitalData_SYNTHETIC.xlsx"

DESIGN <- "stratified"
BOUNDARY_FILE <- "data/synthetic/SYNTHETIC_boundary.csv"
BOUNDARY_IS_HYPOTHETICAL <- TRUE
STRATA_FILE <- "data/synthetic/SYNTHETIC_strata.csv"
STRATUM_AREAS_M2 <- c(dense = 35609, sparse = 20772, channel_edge = 5935)

REPORT_DEPTH_CM <- NULL       # every synthetic core reaches 30 cm, so the headline is measured
SCENARIO_DEPTH_CM <- NULL
OUTPUT_DIR <- "outputs/synthetic"
